### ISSUE TITLE
No upload button after selecting file

### ISSUE THREAD

**Issue by irvinebroque** [webpack/analyse#22] opened 2016-03-03 18:13 UTC
![screen shot 2016-03-03 at 10 00 51 am](https://cloud.githubusercontent.com/assets/1221592/13503934/dbce280c-e126-11e5-9188-98b7cd9b2ca2.png)

**Comment by Kevin-K** [comment] 2016-04-05 15:51
On file selection change it calls the file reader. Check your console log, your `stats.json` may have some prepended text causing the JSON parser to throw an error.

**Comment by maufl** [comment] 2016-04-25 11:04
I have the same problem. When I select a file I get the following error in the console.
`TypeError: t.assets is undefined`

**Comment by mattdell** [comment] 2016-05-31 16:15
This is what I get.

<img width="647" alt="screen shot 2016-05-31 at 18 14 49" src="https://cloud.githubusercontent.com/assets/2536442/15681950/a5e3d96e-275b-11e6-9429-35edacd08dc0.png">

**Comment by Globolobo** [comment] 2016-06-07 18:56
I ran into this as well and i had no idea what was happening. 
I'd say the bug is lack of feedback on what the issue is, suggested solution: display error underneath file upload box.

**Comment by martinratinaud** [comment] 2016-09-29 09:29
Hi guys,

I have an 11Mo file and I get this error

`web.js:1 Uncaught TypeError: Cannot read property 'forEach' of undefined` 

Any idea on how to use the analyse tool ?

Thanks

**Comment by a-r-d** [comment] 2016-10-26 01:21
@irvinebroque marked as an enhancement, the solution should be an error message below the file upload box. If you submit a PR I'll merge it.

**Comment by intellix** [comment] 2018-11-22 10:05
Still doesn't work whatsoever in like 3 years. Thought I'd give it another go since Angular CLI allows you to export stats and recommends this site: `sort of undefined` is the current error

**Closed** 2023-10-10 23:39 UTC
Labels: enhancement
